# image:
#   repository: dhi.io/uptime-kuma

imagePullSecrets:
  - name: dockerhub-credentials

gateway:
  enabled: true
  hostname: status.nulcell.com
  parentRef:
    name: external
    namespace: gateway
    sectionName: https
    httpSectionName: http
  httpRedirect: true

# database:
#   type: mariadb
#   mariadb:
#     hostname: mariadb-cluster
#     port: 3306
#     name: uptime-kuma
#     username: uptime-kuma
#     existingSecret: mariadb-uptime-kuma-password
#     secretPasswordKey: password
