replicaCount: 1

image:
  repository: dhi.io/uptime-kuma

imagePullSecrets:
  - name: dockerhub-credentials
  - name: dhi-credentials

gateway:
  enabled: true
  hostname: status.internal.nulcell.com
  parentRef:
    name: internal
    namespace: gateway
    sectionName: https-internal
    httpSectionName: http
  httpRedirect: true

persistence:
  enabled: false

database:
  type: mariadb
  mariadb:
    hostname: mariadb-cluster
    port: 3306
    name: uptime-kuma
    username: uptime-kuma
    existingSecret: mariadb-uptime-kuma-password
    secretPasswordKey: password
