replicaCount: 1

gateway:
  enabled: true
  host: homepage.nulcell.com

config:
  settings: |
    title: Homecloud
    description: My personal home dashboard.
    startUrl: https://homepage.nulcell.com
    theme: dark
    cardBlur: xs
    color: gray
    language: en
    disableIndexing: true
    headerStyle: boxed
    hideVersion: true
    layout:
      Media:
        sytle: row
        columns: 4
  kubernetes: |
    mode: cluster
    ingress: true
    gateway: true
  bookmarks: |
    - Development:
        - Homecloud GitHub:
            - href: https://github.com/nulcell/homecloud
  services: |
    - Media:
        - Jellyfin:
            href: https://jellyfin.nulcell.com/
        - Radarr:
            href: https://radarr.nulcell.com/
        - Sonarr:
            href: https://sonarr.nulcell.com/
        - Bazarr:
            href: https://bazarr.nulcell.com/
        - Prowlarr:
            href: https://prowlarr.nulcell.com/
        - Seerr:
            href: https://seerr.nulcell.com/

persistence:
  enabled: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
