apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki

helmCharts:
  - name: loki
    repo: https://grafana-community.github.io/helm-charts
    version: 18.7.5
    releaseName: loki
    namespace: loki
    valuesFile: loki-values.yaml
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.11.1
    releaseName: alloy
    namespace: loki
    valuesFile: alloy-values.yaml

resources:
  - namespace.yaml
