apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco

helmCharts:
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: v0.57.6
    releaseName: fluent-bit
    namespace: falco
    valuesFile: fluentbit-values.yaml

resources:
  - falco-instance.yaml
  - plugins.yaml
  # - fluentbit-daemonset.yaml
  - detection-rules.yaml
  - falcosidekick.yaml
  - falcosidekick-ui.yaml
  - falcosidekick-ui-http-routes.yaml
  - metacollector.yaml
