apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-encryption-key
    creationPolicy: Owner
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: fpwjapmya4pjywvazjmehxh57e/n8n-encryption-key # homecloud-k8s/n8n-secrets/n8n-encryption-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-runner-auth
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 3h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-runner-auth
    creationPolicy: Owner
  data:
    - secretKey: auth-token
      remoteRef:
        key: fpwjapmya4pjywvazjmehxh57e/n8n-runner-auth # homecloud-k8s/n8n-secrets/n8n-runner-auth
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
