apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Falco
metadata:
  name: falco
  labels:
    app.kubernetes.io/managed-by: falco-operator
spec:
  type: DaemonSet
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: engine-config
  labels:
    app.kubernetes.io/managed-by: falco-operator
spec:
  config:
    engine:
      kind: modern_ebpf
      modern_ebpf:
        buf_size_preset: 4
        cpus_for_each_buffer: 2
        drop_failed_exit: false
    output_timeout: 2000
    buffered_outputs: false
    outputs_queue:
      capacity: 0
  priority: 50
---
apiVersion: v1
kind: Service
metadata:
  name: falco-k8saudit-proxy
  namespace: falco
spec:
  selector:
    app.kubernetes.io/name: falco
  ports:
    - name: k8saudit
      port: 9765
      targetPort: 9765
      protocol: TCP
