apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Component
metadata:
  name: sidekick
  labels:
    app.kubernetes.io/managed-by: falco-operator
spec:
  component:
    type: falcosidekick
    version: "2.32.0"
  podTemplateSpec:
    spec:
      containers:
        - name: falcosidekick
          env:
            - name: WEBUI_URL
              value: "http://sidekick-ui:2802" # Match the name of your UI service#
            - name: TALON_ADDRESS
              value: "http://falco-talon:2803" # Adjust this to your Talon service name/port
            - name: TALON_MINIMUMPRIORITY
              value: "warning" # Optional: Only forward events at this severity or higher
  replicas: 2
---
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: sidekick-output
spec:
  config:
    json_output: true
    http_output:
      enabled: true
      url: "http://sidekick:2801"
  priority: 50
