apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco

resources:
  - falco-instance.yaml
  - plugins.yaml
  - detection-rules.yaml
  # - falcosidekick.yaml
  # - falcosidekick-ui.yaml
  # - metacollector.yaml
