apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Component
metadata:
  name: metacollector
  labels:
    app.kubernetes.io/managed-by: falco-operator
spec:
  component:
    type: metacollector
    version: "0.1.1"
  replicas: 1
