tty: true

metrics:
  enabled: true

# -- serviceMonitor holds the configuration for the ServiceMonitor CRD.
# A ServiceMonitor is a custom resource definition (CRD) used to configure how Prometheus should
# discover and scrape metrics from the Falco service.
serviceMonitor:
  # -- create specifies whether a ServiceMonitor CRD should be created for a prometheus operator.
  # https://github.com/coreos/prometheus-operator
  # Enable it only if the ServiceMonitor CRD is installed in your cluster.
  create: true

# -- grafana contains the configuration related to grafana.
grafana:
  # -- dashboards contains configuration for grafana dashboards.
  dashboards:
    # -- enabled specifies whether the dashboards should be deployed.
    enabled: true

falco:
  rules_files:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco-incubating_rules.yaml
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  capture:
    # -- Set to true to enable event capturing.
    enabled: true
    # -- Prefix for capture files. Falco appends a timestamp and event number to ensure unique filenames.
    path_prefix: /tmp/falco
    # -- Capture mode. Can be "rules" or "all_rules".
    mode: rules
    # -- Default capture duration in milliseconds if not specified in the rule.
    default_duration: 5000

  # [Stable] `json_output`
  #
  # -- When enabled, Falco will output alert messages and rules file
  # loading/validation results in JSON format, making it easier for downstream
  # programs to process and consume the data. By default, this option is disabled.
  json_output: true

  # [Stable] `http_output`
  #
  # -- Send alerts to an HTTP endpoint or webhook.
  #
  # When using falcosidekick, it is necessary to set `json_output` to true, which is
  # conveniently done automatically for you when using `falcosidekick.enabled=true`.
  http_output:
    # -- Enable sending alerts to an HTTP endpoint or webhook.
    enabled: false
  plugins:
    - name: k8saudit
      library_path: libk8saudit.so
      init_config: ""
      open_params: "http://:9765/k8s-audit"
    - name: json
      library_path: libjson.so
      init_config: ""
  load_plugins: [k8saudit, json]

customRules:
  general-supressions: |
    - rule: "BPF Program Not Profiled"
      override:
        condition: append
      condition:
        and (container.id = "runtime" and evt.type = "bpf" and proc.exepath = "/usr/bin/runc" and proc.pname = "containerd-shim")
  disable-udp-rule.yaml: |
    - rule: "Unexpected UDP Traffic"
      override:
        condition: append
      condition: and (never_true)
  ignore-longhorn-nc.yaml: |
    - rule: "Launch Suspicious Network Tool in Container"
      override:
        condition: append
      condition: and not (k8s.ns.name = "longhorn-system" and container.name = "instance-manager" and proc.name = "nc")
    - rule: "Redirect STDOUT/STDIN to Network Connection in Container"
      override:
        condition: append
      condition: and not (k8s.ns.name = "longhorn-system" and container.name = "instance-manager" and proc.name = "longhorn-instan")
  ignore-gluetun-ping.yaml: |
    - rule: "Redirect STDOUT/STDIN to Network Connection in Container"
      override:
        condition: append
      condition: and not (k8s.ns.name = "media" and container.name = "gluetun" and proc.name = "ping")
  ignore-qbittorrent-ping.yaml: |
    - rule: "Redirect STDOUT/STDIN to Network Connection in Container"
      override:
        condition: append
      condition: and not (k8s.ns.name = "media" and container.name = "qbittorrent" and proc.name = "ping")
  ignore-cilium-cni.yaml: |
    - rule: "Drop and execute new binary in container"
      override:
        condition: append
      condition: and not (container.id = "runtime" and proc.exe = "/opt/cni/bin/cilium-cni")

driver:
  enabled: true
  kind: modern_ebpf
  modernEbpf:
    # -- Constrain Falco with capabilities instead of running a privileged container.
    # Ensure the modern bpf driver is enabled (i.e., setting the `driver.kind` option to `modern_ebpf`).
    # Capabilities used: {CAP_SYS_RESOURCE, CAP_BPF, CAP_PERFMON, CAP_SYS_PTRACE}.
    # Read more on that here: https://falco.org/docs/setup/container/#docker-least-privileged-ebpf-probe
    leastPrivileged: false

falcoctl:
  artifact:
    install:
      enabled: true
    follow:
      enabled: true
  config:
    artifact:
      install:
        refs: [falco-rules:latest, falco-incubating-rules:latest, k8saudit-rules:latest]
      follow:
        refs: [falco-rules:latest, falco-incubating-rules:latest, k8saudit-rules:latest]

# -- Network services configuration (scenario requirement)
# Add here your services to be deployed together with Falco.
services:
  # Example configuration for the "k8sauditlog" plugin
  - name: k8saudit-webhook
    type: ClusterIP
    ports:
      - port: 9765
        targetPort: 9765
        protocol: TCP
        name: http

collectors:
  # -- Enable/disable all the metadata collectors.
  enabled: true
  containerEngine:
    # -- Enable Container Engine support.
    enabled: true
  kubernetes:
    # -- enabled specifies whether the Kubernetes metadata should be collected using the k8smeta plugin and the k8s-metacollector component.
    # It will deploy the k8s-metacollector external component that fetches Kubernetes metadata and pushes them to Falco instances.
    # For more info see:
    # https://github.com/falcosecurity/k8s-metacollector
    # https://github.com/falcosecurity/charts/tree/master/charts/k8s-metacollector
    # When this option is disabled, Falco falls back to the container annotations to grab the metadata.
    # In such a case, only the ID, name, namespace, labels of the pod will be available.
    enabled: true

# -- For configuration values, see https://github.com/falcosecurity/charts/blob/master/charts/falcosidekick/values.yaml
falcosidekick:
  # -- Enable falcosidekick deployment.
  enabled: true
  # -- number of running pods
  replicaCount: 2
  # -- grafana contains the configuration related to grafana.
  grafana:
    # -- dashboards contains configuration for grafana dashboards.
    dashboards:
      # -- enabled specifies whether the dashboards should be deployed.
      enabled: true
  config:
    alertmanager:
      hostport: "http://kps-alertmanager.monitoring:9093"
      minimumpriority: "notice"
      expireafter: 48h # duration string
    talon:
      # -- Talon address, if not empty, Talon output is enabled
      address: "http://falco-talon:2803"
      minimumpriority: "notice"
    webhook:
      # -- Webhook address, if not empty, Webhook output is *enabled*
      address: ""
      # -- HTTP method: POST or PUT
      method: "POST"
      # -- a list of comma separated custom headers to add, syntax is "key:value\,key:value"
      customHeaders: ""
      # -- minimum priority of event to use this output, order is `emergency\|alert\|critical\|error\|warning\|notice\|informational\|debug or ""`
      minimumpriority: ""
      # -- if true, checkcert flag will be ignored (server cert will always be checked)
      mutualtls: false
      # -- check if ssl certificate of the output is valid
      checkcert: true
  ingress:
    # -- Whether to create the ingress
    enabled: false
  webui:
    # -- enable Falcosidekick-UI
    enabled: true
    # -- number of running pods
    replicaCount: 2
    ingress:
      # -- Whether to create the Web UI ingress
      enabled: false
    # -- TTL for keys, the syntax in X<unit>, with <unit>: s, m, d, w (0 for no ttl)
    ttl: 2d
    redis:
      # -- Is mutually exclusive with webui.externalRedis.enabled
      enabled: true
      # -- Enable the PVC for the redis pod
      storageEnabled: true
      # -- Size of the PVC for the redis pod
      storageSize: "1Gi"

# -- Enable the response actions using Falco Talon.
responseActions:
  enabled: true

# -- For configuration values, see https://github.com/falcosecurity/charts/blob/master/charts/falco-talon/values.yaml
# -- It must be used in conjunction with the response_actions.enabled option.
falco-talon:
  # -- number of running pods
  replicaCount: 2
  # -- ingress parameters
  ingress:
    # -- enable the ingress
    enabled: false
  # -- serviceMonitor holds the configuration for the ServiceMonitor CRD.
  serviceMonitor:
    # -- enable the deployment of a Service Monitor for the Prometheus Operator.
    enabled: true
  # -- grafana contains the configuration related to grafana.
  grafana:
    # -- dashboards contains configuration for grafana dashboards.
    dashboards:
      # -- enabled specifies whether the dashboards should be deployed.
      enabled: true
  # -- config of Falco Talon (See https://docs.falco-talon.org/docs/configuration/)
  config:
    # -- default notifiers for all rules
    defaultNotifiers:
      #  - slack
      - k8sevents
    # -- notifiers (See https://docs.falco-talon.org/docs/notifiers/list/ for the settings)
    notifiers:
      # -- webhook
      webhook:
        # -- url
        url: ""

# -- For configuration values, see https://github.com/falcosecurity/charts/blob/master/charts/k8s-metacollector/values.yaml
k8s-metacollector:
  # -- grafana contains the configuration related to grafana.
  grafana:
    # -- dashboards contains configuration for grafana dashboards.
    dashboards:
      # -- enabled specifies whether the dashboards should be deployed.
      enabled: true
