# Placeholder - encrypt before committing real values:
#   sops --encrypt --in-place gitops/infrastructure/sops-secrets/example-secret.enc.yaml
#
# `.sops.yaml` at the repo root selects the age public key and limits encryption
# to data/stringData, leaving the rest readable in diffs.
apiVersion: v1
kind: Secret
metadata:
    name: example
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MEIgFbw=,iv:vKWJH9kiFAhxxO/vo6uv4Opk9fo1+XF+dbA/jz9v534=,tag:FvmHj0G5918x85lMBSgrpw==,type:str]
    password: ENC[AES256_GCM,data:l1JzjbmjoDj0iA==,iv:OiYXtuiFliVAvBWjLVNCV+zS1/6LCrpbCIdPzQwz44E=,tag:5M/n7C4i+656Zx3K1x2zxg==,type:str]
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSlEranJBdUowbTkybXZK
              S2ZTVmFLbHBjN0RmZkQxSVU0Qjg4QmFvVXlFCnA5V2l0WTlHMUhEQ2V2OVVhNEVG
              ekVLaFRCUnBSdExrbkhaOFkwWHJLUnMKLS0tIHMydVFCMW5YVjZFeDdLTDRRbk1J
              OW1SK1Q3QUxNY0V4Z0xvdGNHeE1EUVUK5iSymbdVT9vvw1kcY8DGqWu7wDwVlQx0
              zYrqBjj6ijHlJvuj8bZMz1Dh0462v5OyIkcDJcxBDsk6jzypBV4ypw==
              -----END AGE ENCRYPTED FILE-----
          recipient: age1zghrycrgnan0c7nfp5ke5csdeh9rdgtzwsd6yj4pl9rzlzjp24cspycpul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T09:18:20Z"
    mac: ENC[AES256_GCM,data:c9xm3zTzkyaMrTJvanpqUhVIgcm3W1EfqfzkM9hz4JS3p5zg0Bj3QSXfsCNmmlLfOkqZg35c8HKCisEABWJzSOMjpEuvOeJMLSYS8nkAlrdexQGMjgu+1UTKMFxXkg5b3OUnWvYup/v7TNgTdRGh3UPwYs0BLZzB2Naf2wM+KUE=,iv:pYgp/bQwrNAw5vB2bepJfp+TXJOh7ygAQPtGQOCvs3M=,tag:inJl0zyeqQpG1+wYv9Ty8g==,type:str]
    version: 3.13.0
