# Create an ubuntu bastion host for testing purposes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
        - name: bastion
          image: ubuntu:24.04
          command: ["/bin/sh", "-c", "while true; do sleep 30; done;"]
          securityContext:
            runAsNonRoot: false # Allow running as root for testing purposes
            runAsUser: 0 # Run as root for testing purposes
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - ALL
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
