apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: outline
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 2h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: outline-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret-key # generate with `openssl rand -hex 32` and paste into 1Password
      remoteRef:
        key: h44pyfwssyswg6l2ngg7yj5v3m/secret-key # homecloud-k8s/outline-secrets/secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: utils-secret # generate with `openssl rand -hex 32` and paste into 1Password
      remoteRef:
        key: h44pyfwssyswg6l2ngg7yj5v3m/utils-secret # homecloud-k8s/outline-secrets/utils-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: client-secret
      remoteRef:
        key: h44pyfwssyswg6l2ngg7yj5v3m/oidc-client-secret # homecloud-k8s/outline-secrets/oidc-client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
