apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: {{ include "n8n.namespace" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.ingress.certIssuer }}
    traefik.ingress.kubernetes.io/ssl-host: "{{ .Values.ingress.sslHost }}"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.webPort }}
            path: /
            pathType: Prefix
