apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "n8n.namespace" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.ingress.certIssuer }}
    traefik.ingress.kubernetes.io/ssl-host: "{{ .Values.ingress.sslHost }}"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
  ports:
    - name: "web-port"
      port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.service.webPort }}
    - name: "broker-port"
      port: {{ .Values.service.taskBrokerPort }}
      targetPort: {{ .Values.service.taskBrokerPort }}
