# Inspired by https://github.com/siderolabs/contrib/blob/main/examples/omni/apps/kube-system/cilium/values.yaml
cilium:
  kubeProxyReplacement: true
  policyEnforcementMode: "default"
  ipam:
    mode: cluster-pool # kubernetes or cluster-pool (default is cluster-pool)
    operator:
      clusterPoolIPv4PodCIDRList: ["10.128.0.0/16"]
      clusterPoolIPv4MaskSize: 24
  ipv4:
    enabled: true
  ipv6:
    enabled: false
  securityContext:
    capabilities:
      ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETUID
        - SETGID
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  bgpControlPlane:
    enabled: true
  encryption:
    # -- Enable transparent network encryption.
    enabled: true
    # -- Encryption method. Can be either ipsec or wireguard.
    type: wireguard
    # -- Enable encryption for pure node to node traffic.
    # This option is only effective when encryption.type is set to "wireguard".
    nodeEncryption: true
  k8sNetworkPolicy:
    # -- Enable support for K8s NetworkPolicy
    enabled: true
  ingressController:
    enabled: true
    default: false
    loadbalancerMode: dedicated # dedicated or shared
  gatewayAPI:
    enabled: false
    enableAlpn: false
    enableAppProtocol: false
  hubble:
    enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
  l2announcements:
    enabled: true
  l2podAnnouncements:
    enabled: true
    interface: eth0
  l7Proxy: true
  egressGateway:
    # -- Enables egress gateway to redirect and SNAT the traffic that leaves the cluster.
    enabled: false
  envoy:
    enabled: true
