apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco-operator

helmCharts:
  - name: falco-operator
    repo: https://falcosecurity.github.io/charts
    version: 0.1.0
    releaseName: falco-operator
    namespace: falco-operator
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - namespace.yaml
