# Inspired by https://github.com/siderolabs/contrib/blob/main/examples/omni/apps/kube-system/cilium/values.yaml
cilium:
  kubeProxyReplacement: true
  cni:
    exclusive: true
  socketLB:
    # -- Enable socket LB
    enabled: false
    # -- Disable socket lb for non-root ns. This is used to enable Istio routing rules.
    # hostNamespaceOnly: false
  bpf:
    masquerade: true
  ipv4:
    enabled: true
    masquerade: true
  ipv6:
    enabled: false
  ipam:
    mode: cluster-pool # kubernetes or cluster-pool (default is cluster-pool)
    operator:
      clusterPoolIPv4PodCIDRList:
        - "10.128.0.0/16"
      clusterPoolIPv4MaskSize: 24
  securityContext:
    capabilities:
      ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETUID
        - SETGID
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  bgpControlPlane:
    enabled: true
  encryption:
    # -- Enable transparent network encryption.
    enabled: true
    # -- Encryption method. Can be either ipsec or wireguard.
    type: wireguard
    # -- Enable encryption for pure node to node traffic.
    # This option is only effective when encryption.type is set to "wireguard".
    nodeEncryption: true
  k8sNetworkPolicy:
    # -- Enable support for K8s NetworkPolicy
    enabled: true
  loadBalancer:
    l7:
      # -- Enable L7 service load balancing via envoy proxy.
      # The request to a k8s service, which has specific annotation e.g. service.cilium.io/lb-l7,
      # will be forwarded to the local backend proxy to be load balanced to the service endpoints.
      # Please refer to docs for supported annotations for more configuration.
      #
      # Applicable values:
      #   - envoy: Enable L7 load balancing via envoy proxy. This will automatically set enable-envoy-config as well.
      #   - disabled: Disable L7 load balancing by way of service annotation.
      backend: envoy
  l7Proxy: true
  ingressController:
    enabled: true
    default: true
    loadbalancerMode: dedicated # dedicated or shared
  gatewayAPI:
    enabled: false
    enableAlpn: false
    enableAppProtocol: false
  egressGateway:
    # -- Enables egress gateway to redirect and SNAT the traffic that leaves the cluster.
    enabled: true
  envoy:
    enabled: true
  envoyConfig:
    enabled: true
  l2announcements:
    enabled: true
  l2podAnnouncements:
    enabled: true
    interface: eth0
  hubble:
    enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
  prometheus:
    enabled: true
