apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-encryption
  namespace: homarr
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 2h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: db-encryption
    creationPolicy: Owner
  data:
    - secretKey: db-encryption-key
      remoteRef:
        key: wawmpfjgbyrxgjcztlwactps3u/db-encryption-key # homecloud-k8s/homarr-secrets/db-encryption-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
