{{- if .Values.scaling.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
  namespace: {{ include "n8n.namespace" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "n8nWorker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.scaling.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "n8nWorker.selectorLabels" . | nindent 8 }}
        {{- with .Values.scaling.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.n8n.podSecurityContext | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      enableServiceLinks: false
      containers:
        - name: n8n-worker
          image: "{{ .Values.n8n.image.repository }}:{{ .Values.n8n.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.n8n.image.pullPolicy }}
          command: ["n8n", "worker"]
          env:
            - name: GENERIC_TIMEZONE
              value: {{ .Values.n8n.timezone | quote }}
            - name: TZ
              value: {{ .Values.n8n.timezone | quote }}
            - name: NODE_ENV
              value: production
            - name: N8N_LOG_LEVEL
              value: {{ .Values.n8n.logLevel | default "info" | quote }}
            - name: EXECUTIONS_MODE
              value: queue
            - name: N8N_CONCURRENCY_PRODUCTION_LIMIT
              value: {{ .Values.scaling.worker.concurrency | quote }}
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: {{ .Values.scaling.database.host | quote }}
            - name: DB_POSTGRESDB_PORT
              value: {{ .Values.scaling.database.port | quote }}
            - name: DB_POSTGRESDB_DATABASE
              value: {{ .Values.scaling.database.name | quote }}
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.scaling.database.existingSecret }}
                  key: {{ .Values.scaling.database.secretUsernameKey }}
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.scaling.database.existingSecret }}
                  key: {{ .Values.scaling.database.secretPasswordKey }}
            - name: QUEUE_BULL_REDIS_HOST
              value: {{ .Values.scaling.redis.host | quote }}
            - name: QUEUE_BULL_REDIS_PORT
              value: {{ .Values.scaling.redis.port | quote }}
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.scaling.encryptionKey.existingSecret }}
                  key: {{ .Values.scaling.encryptionKey.secretKey }}
            - name: N8N_RUNNERS_MODE
              value: external
            - name: N8N_RUNNERS_TASK_BROKER_URI
              value: {{ printf "http://%s.%s.svc.cluster.local:5679" .Values.service.name (include "n8n.namespace" .) }}
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.taskRunner.authToken.secretName }}
                  key: {{ .Values.taskRunner.authToken.secretKey }}
            - name: N8N_RUNNERS_EXTERNAL_ALLOW
              value: '*'
            - name: N8N_RUNNERS_STDLIB_ALLOW
              value: '*'
            - name: NODE_FUNCTION_ALLOW_BUILTIN
              value: '*'
            - name: NODE_FUNCTION_ALLOW_EXTERNAL
              value: '*'
          resources:
            {{- toYaml .Values.scaling.worker.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.n8n.containerSecurityContext | nindent 12 }}
      restartPolicy: Always
{{- end }}
