apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-task-runner
  namespace: {{ include "n8n.namespace" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.n8nTaskRunner.replicaCount }}
  selector:
    matchLabels:
      {{- include "n8nTaskRunner.selectorLabels" . | nindent 6 }}
  {{- if .Values.n8nTaskRunner.updateStrategy }}
  strategy:
    {{- toYaml .Values.n8nTaskRunner.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.n8nTaskRunner.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "n8nTaskRunner.selectorLabels" . | nindent 8 }}
        {{- with .Values.n8nTaskRunner.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      enableServiceLinks: true
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      containers:
        - name: n8n-task-runner
          image: "{{ .Values.n8nTaskRunner.image.repository }}:{{ .Values.n8nTaskRunner.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.n8nTaskRunner.image.pullPolicy }}
          env:
            - name: GENERIC_TIMEZONE
              value: {{ .Values.n8n.timezone | quote }}
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.taskRunner.authToken.secretName }}
                  key: {{ .Values.taskRunner.authToken.secretKey }}
            - name: N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT
              value: "15"
            - name: N8N_RUNNERS_EXTERNAL_ALLOW
              value: '*'
            - name: N8N_RUNNERS_LAUNCHER_LOG_LEVEL
              value: {{ .Values.n8nTaskRunner.launcherLogLevel | default "debug" | quote }}
            - name: N8N_RUNNERS_STDLIB_ALLOW
              value: '*'
            - name: N8N_RUNNERS_TASK_BROKER_URI
              value: {{ printf "http://%s.%s.svc.cluster.local:%v" .Values.service.name (include "n8n.namespace" .) .Values.service.taskBrokerPort }}
            - name: NODE_FUNCTION_ALLOW_BUILTIN
              value: '*'
            - name: NODE_FUNCTION_ALLOW_EXTERNAL
              value: '*'
          resources:
            {{- toYaml .Values.n8nTaskRunner.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.n8nTaskRunner.containerSecurityContext | nindent 12 }}
      restartPolicy: Always
