apiVersion: seaweed.seaweedfs.com/v1
kind: Bucket
metadata:
  name: sample
  namespace: media
spec:
  anonymousRead: true
  clusterRef:
    name: seaweedfs
    namespace: seaweedfs
  quota:
    enforce: true
    size: 1Gi
  objectLock: false
  reclaimPolicy: Delete
  versioning: Enabled
