apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt
  labels:
    pod-security.kubernetes.io/enforce: privileged    # KubeVirt needs privileged for virt-handler
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
