# ⚠ Plaintext placeholder — encrypt before committing real values:
#   sops --encrypt --in-place kubernetes-infrastructure/gitops/infrastructure/gateway/cloudflare-token.enc.yaml
#
# Token scope: Zone → DNS → Edit, restricted to the nulcell.com zone only.
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:AZpC2fTCG9NKM1D7iyjUnR+oyddxVT88dbe40eYaD1929SodFYW57A==,iv:sMMvYJ8K+IIXIlG89GtYoygSDyu6JJnqXcD8W6t1+Z8=,tag:PNhYYxwC728bAXL7grrY5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eGJ4Njd2ZjYwZ2s0VFc2
        Q1lJNUdFNjNVUm90NTFLT1pWT1Y4a3ZidUJFCnBoS04vZGpmTS9XalhsTWhVV1hr
        T1g4czh2cTRUbHN6V1pjNzJ6dW01a1kKLS0tIHhkK0MveDFhQUxSU01vdk9rV3RP
        K1QwOXRVR3RwUW1iYmFmaDk0WVJCcE0KUjoXntAg0hBW6HkK9FTsjEjEe0Md0ByS
        2TksZ8zlcxPv789W9I5/SG/onaaCROmjUAhD11Kvg8sQeBvWbO2Hug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zghrycrgnan0c7nfp5ke5csdeh9rdgtzwsd6yj4pl9rzlzjp24cspycpul
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T08:03:54Z"
  mac: ENC[AES256_GCM,data:P45nvtNLNCiw8QOdz19EBjNcKCFc4Qwq08uKnOu2Dq/AcKD2PjmXYxCKCAJwz1YhASSdmwZUmgrJg/uR+eIpA5nfy7UVZwvPVgW3DObIh3pinkEsjgiotfayLyshNJseeBFAgxvIRilaA83cmkh7StuP+cCXm6HfoXTbxTaECAc=,iv:M8I4VwGSAbgrVbAdD+WKYEuCSRaf/W9kdzv18Fk++m8=,tag:ek0GNmlkjc997T1SWehAGA==,type:str]
  version: 3.13.0
