apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway
resources:
  - namespace.yaml
  - gatewayclass.yaml
  - clusterissuer.yaml
  - wildcard-certificate.yaml
  - gateway-default.yaml
generators:
  - secret-generator.yaml
