traefik:
  additionalArguments:
    - --certificatesresolvers.le.acme.storage=/data/acme.json
    - --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare
    - --certificatesResolvers.le.acme.dnsChallenge.resolvers=1.1.1.1:53
    - --api=true
  # Traefik experimental features
  experimental:
    # -- Defines whether all plugins must be loaded successfully for Traefik to start
    abortOnPluginFailure: false
    fastProxy:
      # -- Enables the FastProxy implementation.
      enabled: false
      # -- Enable debug mode for the FastProxy implementation.
      debug: false
    kubernetesGateway:
      # -- Enable traefik experimental GatewayClass CRD
      enabled: false
    # -- Enable experimental plugins
    plugins: {}
    # -- Enable experimental local plugins
    localPlugins: {}
    # -- Enable OTLP logging experimental feature.
    otlpLogs: false
    # -- Enable Knative provider experimental feature.
    knative: false

  gateway:
    # -- When providers.kubernetesGateway.enabled, deploy a default gateway
    enabled: true

  # -- Create a default IngressClass for Traefik
  ingressClass: # @schema additionalProperties: false
    enabled: true
    isDefaultClass: false
    name: ""

  gatewayClass: # @schema additionalProperties: false
    # -- When providers.kubernetesGateway.enabled and gateway.enabled, deploy a default gatewayClass
    enabled: true

  api:
    # -- Enable the dashboard
    dashboard: true
    # -- Configure API basePath
    basePath: "" # @schema type:[string, null]; default: "/"

  ingressRoute:
    dashboard:
      # -- Create an IngressRoute for the dashboard
      enabled: true # optional
      # -- The router match rule used for the dashboard ingressRoute
      matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      entryPoints: ["websecure"]
      # -- The internal service used for the dashboard ingressRoute
      services:
        - name: api@internal
          kind: TraefikService
    healthcheck:
      # -- Create an IngressRoute for the healthcheck probe
      enabled: true # optional

  providers: # @schema additionalProperties: false
    kubernetesCRD:
      # -- Load Kubernetes IngressRoute provider
      enabled: true
      # -- Allows IngressRoute to reference resources in namespace other than theirs
      allowCrossNamespace: false
      # -- Allows to reference ExternalName services in IngressRoute
      allowExternalNameServices: false
      # -- Allows to return 503 when there is no endpoints available
      allowEmptyServices: true
      # -- When the parameter is set, only resources containing an annotation with the same value are processed. Otherwise, resources missing the annotation, having an empty value, or the value traefik are processed. It will also set required annotation on Dashboard and Healthcheck IngressRoute when enabled.
      ingressClass: ""
      # labelSelector: environment=production,method=traefik
      # -- Array of namespaces to watch. If left empty, Traefik watches all namespaces. . When using `rbac.namespaced`, it will watch helm release namespace and namespaces listed in this array.
      namespaces: []
      # -- Defines whether to use Native Kubernetes load-balancing mode by default.
      nativeLBByDefault: false

    kubernetesIngress:
      # -- Load Kubernetes Ingress provider
      enabled: true
      # -- Allows to reference ExternalName services in Ingress
      allowExternalNameServices: false
      # -- Allows to return 503 when there is no endpoints available
      allowEmptyServices: true
      # -- When ingressClass is set, only Ingresses containing an annotation with the same value are processed. Otherwise, Ingresses missing the annotation, having an empty value, or the value traefik are processed.
      ingressClass: # @schema type:[string, null]
      # labelSelector: environment=production,method=traefik
      # -- Array of namespaces to watch. If left empty, Traefik watches all namespaces. . When using `rbac.namespaced`, it will watch helm release namespace and namespaces listed in this array.
      namespaces: []
      # IP used for Kubernetes Ingress endpoints
      publishedService:
        # -- Enable [publishedService](https://doc.traefik.io/traefik/providers/kubernetes-ingress/#publishedservice)
        enabled: true
        # -- Override path of Kubernetes Service used to copy status from. Format: namespace/servicename.
        # Default to Service deployed with this Chart.
        pathOverride: ""
      # -- Defines whether to use Native Kubernetes load-balancing mode by default.
      nativeLBByDefault: false

    kubernetesGateway:
      # -- Enable Traefik Gateway provider for Gateway API
      enabled: true
      # -- Toggles support for the Experimental Channel resources (Gateway API release channels documentation).
      # This option currently enables support for TCPRoute and TLSRoute.
      experimentalChannel: false
      # -- Array of namespaces to watch. If left empty, Traefik watches all namespaces. . When using `rbac.namespaced`, it will watch helm release namespace and namespaces listed in this array.
      namespaces: []
      # -- A label selector can be defined to filter on specific GatewayClass objects only.
      labelselector: ""
      # -- Defines whether to use Native Kubernetes load-balancing mode by default.
      nativeLBByDefault: false
      statusAddress:
        # -- This IP will get copied to the Gateway status.addresses, and currently only supports one IP value (IPv4 or IPv6).
        ip: ""
        # -- This Hostname will get copied to the Gateway status.addresses.
        hostname: ""
        # -- The Kubernetes service to copy status addresses from. When using third parties tools like External-DNS, this option can be used to copy the service loadbalancer.status (containing the service's endpoints IPs) to the gateways. Default to Service of this Chart.
        service:
          enabled: true
          name: ""
          namespace: ""

  service:
    enabled: true
    ## -- Single service is using `MixedProtocolLBService` feature gate.
    ## -- When set to false, it will create two Service, one for TCP and one for UDP.
    single: true
    type: LoadBalancer

  env:
    - name: CF_DNS_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: credential
    - name: CF_API_EMAIL
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: username

  autoscaling:
    # -- Create HorizontalPodAutoscaler object.
    # See EXAMPLES.md for more details.
    enabled: false

  # -- Enable to create a PodSecurityPolicy and assign it to the Service Account via RoleBinding or ClusterRoleBinding
  podSecurityPolicy:
    enabled: false

  # -- The service account the pods will use to interact with the Kubernetes API
  serviceAccount: # @schema additionalProperties: false
    # If set, an existing service account is used
    # If not set, a service account is created automatically using the fullname template
    name: ""

  # -- [SecurityContext](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1)
  # @default -- See _values.yaml_
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
    readOnlyRootFilesystem: true

  # -- [Pod Security Context](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context)
  # @default -- See _values.yaml_
  podSecurityContext:
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
    fsGroup: 65532 # https://github.com/traefik/traefik-helm-chart/issues/164 (use 65532 on first install if you need it)

  persistence:
    # -- Enable persistence using Persistent Volume Claims
    # ref: http://kubernetes.io/docs/user-guide/persistent-volumes/.
    # It can be used to store TLS certificates along with `certificatesResolvers.<name>.acme.storage`  option
    enabled: true
    name: data
    existingClaim: ""
    accessMode: ReadWriteOnce
    size: 128Mi
    storageClass: "cloudstack-custom-disk-offering"
    volumeName: ""
    path: /data
    annotations: {}
    # -- Only mount a subpath of the Volume into the pod
    subPath: ""

  deployment:
    initContainers:
      # The "volume-permissions" init container is required if you run into permission issues.
      # Related issue: https://github.com/traefik/traefik-helm-chart/issues/396
      - name: volume-permissions
        image: busybox:latest
        command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
        volumeMounts:
          - name: data
            mountPath: /data

  metrics:
    # -- Enable metrics exposing
    enabled: true
    # -- Prometheus metrics configuration
    prometheus:
      # -- Enable Prometheus metrics endpoint
      enabled: true
      # -- Metrics entryPoint
      entryPoint: "metrics"
