apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: seaweedfs-operator
    repo: https://seaweedfs.github.io/seaweedfs-operator/
    version: 0.1.36
    releaseName: seaweedfs-operator
    namespace: seaweedfs-operator
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - namespaces.yaml
