apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: dhi-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: n8n
    - matchLabels:
        kubernetes.io/metadata.name: authentik
    - matchLabels:
        kubernetes.io/metadata.name: media
    - matchLabels:
        kubernetes.io/metadata.name: actual-budget
    - matchLabels:
        kubernetes.io/metadata.name: kubescape
    - matchLabels:
        kubernetes.io/metadata.name: tailscale
    - matchLabels:
        kubernetes.io/metadata.name: cloudflared
    - matchLabels:
        kubernetes.io/metadata.name: homarr
    - matchLabels:
        kubernetes.io/metadata.name: uptime-kuma
    - matchLabels:
        kubernetes.io/metadata.name: outline
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: dhi-credentials
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: pzswbuyydtf2icbytldxolt3ju/config # homecloud-k8s/dhi-credentials/config
          conversionStrategy: Default
          decodingStrategy: Base64
          metadataPolicy: None
          nullBytePolicy: Ignore
    refreshInterval: 2h

# Create config value with the following command:
# kubectl create secret docker-registry regcred \
# --docker-server=https://dhi.io \
# --docker-username=$(op read "op://homecloud/Docker Registry Read PAT/username") \
# --docker-password=$(op read "op://homecloud/Docker Registry Read PAT/password") \
# --dry-run=client -o json | jq ".data"
