apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: dockerhub-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: n8n
    - matchLabels:
        kubernetes.io/metadata.name: authentik
    - matchLabels:
        kubernetes.io/metadata.name: media
    - matchLabels:
        kubernetes.io/metadata.name: actual-budget
    - matchLabels:
        kubernetes.io/metadata.name: kubescape
    - matchLabels:
        kubernetes.io/metadata.name: tailscale
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: dockerhub-credentials
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: dockerhub-credentials/config
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
