{{- if .Values.seerr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mediaStack.labels" (dict "ctx" . "app" "seerr") | nindent 4 }}
spec:
  type: {{ .Values.seerr.service.type }}
  selector:
    {{- include "mediaStack.selectorLabels" (dict "ctx" . "app" "seerr") | nindent 4 }}
  ports:
    - name: web
      port: {{ .Values.seerr.service.ports.web }}
      targetPort: {{ .Values.seerr.service.ports.web }}
      protocol: TCP
{{- end }}
