{{- if .Values.tdarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tdarr
  namespace: {{ include "mediaStack.namespace" . }}
  labels:
    {{- include "mediaStack.labels" (dict "ctx" . "app" "tdarr") | nindent 4 }}
spec:
  type: {{ .Values.tdarr.service.type }}
  selector:
    {{- include "mediaStack.selectorLabels" (dict "ctx" . "app" "tdarr") | nindent 4 }}
  ports:
    - name: web
      port: {{ .Values.tdarr.service.ports.web }}
      targetPort: {{ .Values.tdarr.service.ports.web }}
      protocol: TCP
    - name: server
      port: {{ .Values.tdarr.service.ports.server }}
      targetPort: {{ .Values.tdarr.service.ports.server }}
      protocol: TCP
{{- end }}
