# Plaintext placeholder — encrypt before committing:
#   sops --encrypt --in-place kubernetes-infrastructure/gitops/apps-testing/media-stack/vpn-credentials.enc.yaml
#
# For NordVPN OpenVPN, the values are your service credentials (NOT your account
# login). Get them from https://my.nordaccount.com/dashboard/nordvpn/
apiVersion: v1
kind: Secret
metadata:
    name: media-stack-vpn
    namespace: media
type: Opaque
stringData:
    openvpn-user: ENC[AES256_GCM,data:OajM0gQZB07Qb5hJAEdOvk6Svf8HdKk3,iv:114LPz2de7FMXMYvDL1QltvBQo9k7sriHxVLr3SWCGI=,tag:EQy8jSXUOGva+lz1/Q3JfA==,type:str]
    openvpn-password: ENC[AES256_GCM,data:ZIRlbIRWP7tRGvTKKv4WcKoFwMiHITEK,iv:IvYjpz/xGiPmgeDfTkJp5CPCHBjjd/wUGtefSqpU3AI=,tag:56jXp5pEoo7YVsALETpX/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRmQ5UWJHY1VUNEpUZG1h
            aTBiNjZwc3diWC9VTVR2MkJ5TCtHQ3d6bm1vCkdsNm91dW5ITlBKOVVyK3UybnBv
            cDBUTkZPeXg0M0Nwb2RkZnNzTHM4d0kKLS0tIEdtV0hPbFVsbnB2UG1xdDJnclJ5
            OFJpRHg5UHFpNjlBeDloQmEyZE5DYmMKgZYGb30jlXxA6sbD2AKX2ib/CGAoImNN
            s8GyNfwIt0qAtnh+6GuRVwMNDKirnLMcrNxtsv1R58RNL0TG46DUzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zghrycrgnan0c7nfp5ke5csdeh9rdgtzwsd6yj4pl9rzlzjp24cspycpul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T13:15:23Z"
    mac: ENC[AES256_GCM,data:foWuSDrwyYoRW8wHuv813WrR0k1fqv28RykoMKnaMRxDKOlfujoZavgv2rbp95ev7DQat7pofM3BIziz1+rItC8PB3otF0Hknhc2WwFsdXNzszTttYmOrU2luDaRQRReCoaeZDEUP2qbGfTveQ8htsicGTBZenKn3rDbNh8Vj+M=,iv:w+zu+7Nbt37W319l0gCjo18UZkWY9pcrry94vrCcBAE=,tag:cIG6Dsu9Ez9ewZgtYN/fbQ==,type:str]
    version: 3.13.0
