apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    onepasswordSDK:
      vault: homecloud
      auth:
        serviceAccountSecretRef:
          name: onepassword-credentials
          namespace: external-secrets
          key: credential
