apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    onepasswordSDK:
      vault: f5icrhdwdm7hrsnogmipwpoaxm # homecloud-k8s
      auth:
        serviceAccountSecretRef:
          name: onepassword-credentials
          namespace: external-secrets
          key: credential
      cache:
        ttl: 5m # Optional, default: 5m
        maxSize: 100 # Optional, default: 100
  refreshInterval: 7200 # 2 hours
