apiVersion: v2
name: monitoring
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 80.4.2
    repository: oci://ghcr.io/prometheus-community/charts
  # - name: loki
  #   version: 6.49.0
  #   repository: https://grafana.github.io/helm-charts
