clusterName: homecloud

capabilities:
  configurationScan: enable
  vulnerabilityScan: enable
  runtimeObservability: enable
  kubescapeOffline: enable
  continuousScan: enable
  admissionController: disable

kubescape:
  serviceMonitor:
    enabled: true

nodeAgent:
  serviceMonitor:
    enabled: true
