apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seaweedfs

helmCharts:
  - name: seaweedfs-operator
    repo: https://seaweedfs.github.io/seaweedfs-operator/
    version: 0.1.23
    releaseName: seaweedfs-operator
    namespace: seaweed
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - namespace.yaml
