apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-nulcell
  namespace: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: wildcard-nulcell-tls # consumed by gateway-default.yaml
  duration: 2160h # 90 days
  renewBefore: 720h # renew 30 days before expiry
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-nulcell-com
  commonName: "*.nulcell.com"
  dnsNames:
    - nulcell.com
    - "*.nulcell.com"
