apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-cert-pem
  namespace: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-cert-pem
    creationPolicy: Owner
  data:
    - secretKey: cert.pem
      remoteRef:
        key: cloudflared-secrets/cert-pem
        conversionStrategy: Default
        decodingStrategy: Base64
        metadataPolicy: None
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials-json
  namespace: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-credentials-json
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: cloudflared-secrets/credentials-json
        conversionStrategy: Default
        decodingStrategy: Base64
        metadataPolicy: None
        nullBytePolicy: Ignore
