# -- This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replica:
  # -- This will use DaemonSet to deploy cloudflared to all nodes
  allNodes: false
  # -- If previous flag disabled, this will use Deployment to deploy cloudflared only number of following count
  count: 2

tunnelConfig:
  # Must match the tunnel name you created with: cloudflared tunnel create <name>
  name: homecloud-k8s
  logLevel: info
  protocol: auto

tunnelSecrets:
  existingPemFileSecret:
    name: cloudflared-cert-pem
    key: cert.pem
  existingConfigJsonFileSecret:
    name: cloudflared-credentials-json
    key: credentials.json

ingress:
  - hostname: n8n.nulcell.com
    service: http://n8n.n8n.svc.cluster.local:5678
  - service: http_status:404

imagePullSecrets:
  - name: dockerhub-credentials

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
