{{- if .Values.falcosidekickUi.enabled }}
{{- $redisAddr := .Values.falcosidekickUi.redisAddr -}}
{{- if and .Values.redis.enabled (not $redisAddr) -}}
  {{- $redisAddr = printf "%s.%s.svc:6379" .Values.redis.serviceName (include "falcoStack.namespace" .) -}}
{{- end }}
apiVersion: instance.falcosecurity.dev/v1alpha1
kind: Component
metadata:
  name: falcosidekick-ui
  namespace: {{ include "falcoStack.namespace" . }}
  labels:
    {{- include "falcoStack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  component:
    type: falcosidekick-ui
  replicas: {{ .Values.falcosidekickUi.replicas }}
  podTemplateSpec:
    spec:
      {{- if $redisAddr }}
      initContainers:
        - name: wait-redis
          env:
            - name: REDIS_ADDR
              value: {{ $redisAddr | quote }}
      {{- end }}
      containers:
        - name: falcosidekick-ui
          {{- if $redisAddr }}
          args:
            - "-r"
            - {{ $redisAddr | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.falcosidekickUi.resources | nindent 12 }}
{{- end }}
