{{- $ns := include "falcoStack.namespace" . -}}
{{- $httpURL := .Values.outputs.http.url -}}
{{- if and .Values.outputs.http.enabled (not $httpURL) -}}
  {{- $httpURL = printf "http://falcosidekick.%s.svc:2801" $ns -}}
{{- end -}}
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: falco-output
  namespace: {{ $ns }}
  labels:
    {{- include "falcoStack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  config:
    json_output: {{ .Values.outputs.json }}
    stdout_output:
      enabled: {{ .Values.outputs.stdout.enabled }}
    {{- if .Values.outputs.http.enabled }}
    http_output:
      enabled: true
      url: {{ $httpURL | quote }}
    {{- end }}
    {{- if .Values.outputs.metrics.enabled }}
    metrics:
      enabled: true
      interval: {{ .Values.outputs.metrics.interval }}
      output_rule: true
      include_empty_values: false
      rules_counters_enabled: true
      resource_utilization_enabled: true
      state_counters_enabled: true
      kernel_event_counters_enabled: true
      libbpf_stats_enabled: true
      convert_memory_to_mb: true
      prometheus_text_format: {{ .Values.outputs.metrics.promTextFormat }}
    {{- end }}
    {{- if .Values.outputs.webserver.enabled }}
    webserver:
      enabled: true
      listen_port: {{ .Values.outputs.webserver.listenPort }}
      k8s_healthz_endpoint: /healthz
      prometheus_metrics_enabled: {{ .Values.outputs.metrics.enabled }}
      ssl_enabled: {{ .Values.outputs.webserver.sslEnabled }}
      threadiness: 0
    {{- end }}
  priority: 60
