{{- if .Values.plugins.container.enabled }}
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Plugin
metadata:
  name: container
  namespace: {{ include "falcoStack.namespace" . }}
  labels:
    {{- include "falcoStack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  ociArtifact:
    image:
      repository: {{ .Values.plugins.container.plugin.ociArtifact.repository }}
      tag: {{ .Values.plugins.container.plugin.ociArtifact.tag }}
    registry:
      name: {{ .Values.plugins.container.plugin.ociArtifact.registry }}
{{- end }}
