{{- if and .Values.plugins.k8saudit.enabled .Values.plugins.k8saudit.rules.enabled }}
apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Rulesfile
metadata:
  name: k8saudit-rules
  namespace: {{ include "falcoStack.namespace" . }}
  labels:
    {{- include "falcoStack.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  ociArtifact:
    image:
      repository: {{ .Values.plugins.k8saudit.rules.ociArtifact.repository }}
      tag: {{ .Values.plugins.k8saudit.rules.ociArtifact.tag }}
    registry:
      name: {{ .Values.plugins.k8saudit.rules.ociArtifact.registry }}
  priority: {{ .Values.plugins.k8saudit.rules.priority }}
{{- end }}
