apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: n8n-runner-auth-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - n8n-runner-auth.enc.yaml
