apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: backup-s3
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: longhorn-system
    - matchLabels:
        kubernetes.io/metadata.name: gatus
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: backup-s3
      creationPolicy: Owner
    data:
      - secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          key: ajs275d32cembcy7b5ubvuwjx4/AWS_ACCESS_KEY_ID # homecloud-k8s/backup-s3/AWS_ACCESS_KEY_ID
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
          nullBytePolicy: Ignore
      - secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          key: ajs275d32cembcy7b5ubvuwjx4/AWS_SECRET_ACCESS_KEY
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
          nullBytePolicy: Ignore
    refreshInterval: 2h
