# Plaintext placeholder — encrypt before committing:
#   sops --encrypt --in-place gitops/infrastructure/kube-prometheus-stack/grafana-admin.enc.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:Co5iCws=,iv:udtn3KZNcW8bs3bDfhVo6CxeSYwOUBG8gFEOZ3COSe4=,tag:+38XykTz6a+dIufkcudnnA==,type:str]
  admin-password: ENC[AES256_GCM,data:uzdD/41tnRECc6xGHMkQTofh7RcIRp+S,iv:TRuJ1hromE2sE3xV+UtxS2IF4wQPVuAd6gUTkA0TVRU=,tag:6P3KxpD4h2C+hJWsrr0gYA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQnVVNG5XWURFbjJIUDZt
        Z3U1L2ZTaWxrNm5JbHllNFFkMTFNNnR6dDFVCk9wN2RMcnJUV3IvQW55eWo2dy81
        WWhxR0Z3Wm5yUXVuMjBSNk93WEtIVDgKLS0tIHQ3NERVbFJSQUtJOExOR0w3K0Ju
        RGpxZWZqTjh1QS9JQVNKcXBzUTJnamcKpqSkOpu/6ZQu6BRqJtVHNW96bkXR8w7g
        buZ3X5ei6S0jDVtZ2YW8pkVRsND86MdfTxcDbg+edHBnA1AWFRYfLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zghrycrgnan0c7nfp5ke5csdeh9rdgtzwsd6yj4pl9rzlzjp24cspycpul
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-16T10:30:09Z"
  mac: ENC[AES256_GCM,data:L8LwaPY/q2TGcpMXQ+pb0c5CtC7dYiK3wsc6/XDbemOTAHS0KRUeIrv5g040+qYwQ3hseKdDniwqJouC/mJc1v9tvegznes4sc7tGQsHFMldRTD9Ial7+NR8EBGJ7ZAMY/DpFAg377IXKfouHhg2Qyu80UlFnfPVRTzxbbPj2MI=,iv:PrD4AfK7Ol+MBtZF+SZXU7eFO89vPxyzknRsltSQNE4=,tag:jPsY5Qovh/uV07/KLzCg8A==,type:str]
  version: 3.13.0
