apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: homecloud-cks
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: homecloud-cks-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta3
    kind: CloudStackCluster
    name: homecloud-cks
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta3
kind: CloudStackCluster
metadata:
  name: homecloud-cks
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 10.10.20.40
    port: 6443
  failureDomains:
    - acsEndpoint:
        name: cloudstack-credentials
        namespace: default
      name: failure-domain-1
      zone:
        name: zone-homecloud
        network:
          name: homecloud-vpc_pub-net-1
  syncWithACS: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: homecloud-cks-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: cloudstack:///'{{ ds.meta_data.instance_id }}'
        name: "{{ local_hostname }}"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: cloudstack:///'{{ ds.meta_data.instance_id }}'
        name: "{{ local_hostname }}"
    preKubeadmCommands:
      - swapoff -a
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta3
      kind: CloudStackMachineTemplate
      name: homecloud-cks-control-plane-2 # Reference to the CloudStackMachineTemplate. Update as needed.
  replicas: 1
  version: v1.32.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta3
kind: CloudStackMachineTemplate
metadata:
  name: homecloud-cks-control-plane-2
  namespace: default
spec:
  template:
    spec:
      offering:
        name: mem.medium.fixed
      sshKey: nulcell
      template:
        name: capi-v1.32.3-ubuntu-2204-kvm
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: homecloud-cks-md-0
  namespace: default
spec:
  clusterName: homecloud-cks
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: homecloud-cks-md-1 # Reference to the KubeadmConfigTemplate for worker nodes. Update as needed.
      clusterName: homecloud-cks
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta3
        kind: CloudStackMachineTemplate
        name: homecloud-cks-md-1 # Reference to the CloudStackMachineTemplate for worker nodes. Update as needed to deploy different instance types.
      version: v1.32.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta3
kind: CloudStackMachineTemplate
metadata:
  name: homecloud-cks-md-1
  namespace: default
spec:
  template:
    spec:
      offering:
        name: gen.1xlarge.fixed
      sshKey: nulcell
      template:
        name: capi-v1.32.3-ubuntu-2204-kvm
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: homecloud-cks-md-1
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            provider-id: cloudstack:///'{{ ds.meta_data.instance_id }}'
          name: "{{ local_hostname }}"
      preKubeadmCommands:
        - swapoff -a
