apiVersion: v2
name: n8n
description: n8n workflow automation tool - Helm Chart
icon: https://n8n.io/brandguidelines/logo-dark.svg
type: application
version: "2.21.7"
appVersion: "2.21.7"
sources:
  - https://github.com/nulcell/homecloud
keywords:
  - n8n
  - workflow
  - automation
home: https://n8n.io
maintainers:
  - name: Salimon Ayanleye
    email: cloud@nulcell.com
