n8n:
  replicaCount: 1

  image:
    repository: docker.n8n.io/n8nio/n8n
    pullPolicy: IfNotPresent
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: "2.0.2"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  namespaceOverride: ""

  # -- Update strategy for the deployment.
  # ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  # For example:
  #  type: RollingUpdate
  #  rollingUpdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  updateStrategy: {}

  # -- Annotations to be added to the pod.
  podAnnotations: {}
  # -- Labels to be added to the pod.
  podLabels: {}

  # -- Container Security Context.
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      add:
        - "ALL"
      drop:
        - "NET_ADMIN"
        - "SYS_ADMIN"

  # -- Security Context for the whole pod.
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    fsGroup: 1000

  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi
    # If you want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #
    # limits:
    #   cpu: 100m
    #   memory: 200Mi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi

n8nTaskRunner:
  replicaCount: 1

  image:
    repository: n8nio/runners
    pullPolicy: IfNotPresent
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: "2.0.2"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  namespaceOverride: ""

  # -- Update strategy for the deployment.
  # ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  # For example:
  #  type: RollingUpdate
  #  rollingUpdate:
  #    maxSurge: 25%
  #    maxUnavailable: 25%
  updateStrategy: {}

  # -- Annotations to be added to the pod.
  podAnnotations: {}
  # -- Labels to be added to the pod.
  podLabels: {}

  # -- Container Security Context.
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      add:
        - "ALL"
      drop:
        - "NET_ADMIN"
        - "SYS_ADMIN"

  # -- Security Context for the whole pod.
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    # fsGroup: 1000

  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi
    # If you want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    #
    # limits:
    #   cpu: 100m
    #   memory: 200Mi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi

hostNetwork: false
dnsPolicy: "ClusterFirst"

# -- Annotations to be added to all other resources.
commonAnnotations: {}
# -- Priority indicates the importance of a Pod relative to other Pods.
priorityClassName: ""

service:
  type: ClusterIP
  # -- DO NOT CHANGE THE SERVICE NAME
  # and can not be configured
  name: n8n
  webPort: 5678
  taskBrokerPort: 5679

ingress:
  # -- Ingress class name
  className: traefik
  # -- Hostname to your n8n installation
  host: n8n.nulcell.com
  # -- Certificate issuer for the ingress
  certIssuer: le
  # -- SSL host for the ingress
  sslHost: "*.nulcell.com"

persistence:
  # -- Enable persistence for n8n files
  enabled: true
  # -- Storage class for n8n files PVC
  storageClass: cloudstack-custom-disk-offering
  # -- Size of the volume for n8n files PVC
  size: 1Gi
