apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: portfolio
    releaseName: portfolio
    namespace: portfolio
    valuesFile: values.yaml
    includeCRDs: false

resources:
  - namespace.yaml
