apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tetragon

helmCharts:
  - name: tetragon
    repo: https://helm.cilium.io
    version: 1.7.0
    releaseName: tetragon
    namespace: tetragon
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - namespace.yaml
