apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: speedtest-tracker

resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - pvc.yaml
  - speedtest-external-secrets.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml
