replicaCount: 1

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteMany
  size: 10Gi

ingress:
  enabled: false

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

login:
  method: password
  allowedLoginMethods:
    - password
