apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-secrets
  namespace: mealie
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 2h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mealie-secrets
    creationPolicy: Owner
  data:
    - secretKey: oidc-client-secret # client secret from Authentik's mealie OAuth2 provider
      remoteRef:
        key: REPLACE_WITH_1PASSWORD_ITEM_ID/oidc-client-secret # homecloud-k8s/mealie-secrets/oidc-client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
