# Cinder LVM backend overrides
# Applied to /etc/kolla/config/cinder/cinder-volume.conf by kolla-ansible.

[DEFAULT]
enabled_backends = lvm-1

[lvm-1]
volume_group = cinder-volumes
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_backend_name = lvm-1
target_protocol = iscsi
target_helper = lioadm
lvm_type = thin
