apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

helmCharts:
  - name: app-template
    repo: oci://ghcr.io/nulcell/charts
    version: 0.3.5
    releaseName: media-stack
    namespace: media
    valuesFile: values.yaml
    includeCRDs: false

resources:
  - namespace.yaml
