apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: media-stack-vpn-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - vpn-credentials.enc.yaml
