apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-stack-vpn
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: media-stack-vpn
    creationPolicy: Owner
  data:
    - secretKey: openvpn-user
      remoteRef:
        key: nordvpn/openvpn-user
    - secretKey: openvpn-password
      remoteRef:
        key: nordvpn/openvpn-password
    - secretKey: wireguard-private-key
      remoteRef:
        key: nordvpn/wireguard-private-key
