apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-stack-vpn
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 2h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: media-stack-vpn
    creationPolicy: Owner
  data:
    - secretKey: openvpn-user
      remoteRef:
        key: za2fsoqefbny5mbvdbx6zclvpy/openvpn-user # homecloud-k8s/nordvpn/openvpn-user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: openvpn-password
      remoteRef:
        key: za2fsoqefbny5mbvdbx6zclvpy/openvpn-password # homecloud-k8s/nordvpn/openvpn-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: wireguard-private-key
      remoteRef:
        key: za2fsoqefbny5mbvdbx6zclvpy/wireguard-private-key # homecloud-k8s/nordvpn/wireguard-private-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
