# Plaintext placeholder — encrypt before committing:
#   sops --encrypt --in-place gitops/apps/media-stack/vpn-credentials.enc.yaml
#
# For NordVPN OpenVPN, the values are your service credentials (NOT your account
# login). Get them from https://my.nordaccount.com/dashboard/nordvpn/
apiVersion: v1
kind: Secret
metadata:
    name: media-stack-vpn
    namespace: media
type: Opaque
stringData:
    openvpn-user: ENC[AES256_GCM,data:+kvZCUA0jcuyCKEqulgM75zKFjn+xX3U,iv:jPx0juBeTnZjwJwurKUJjAasPQUbHz9DCwpiNomtDs8=,tag:dG75BzndyYG/G89rzwHbBw==,type:str]
    openvpn-password: ENC[AES256_GCM,data:85H43/hJ6tCKmQanljldhgWSlXVlNYct,iv:3Qj+P4pyxayDbgumqIE3L2P2qvIl//Z56Xe1YDLbHCY=,tag:FD3QCHHW1jY9P/Fw21yHGg==,type:str]
    wireguard-private-key: ENC[AES256_GCM,data:GZGUukF18jQFdGWFqE5PdrD03JwxmfLj2FrPWogUhpYqxkk/KbGeMMGgzII=,iv:d5/0YMe6yVUoMB8hQd/lCOaWu2H7xE9SHP1/cxzO+OA=,tag:07X2A0YWUW8QrNGw7/c1DA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQU12MWtRRDlacGpBelZI
            K2M2OUZrcnV1UTY1VTViemFLREh1NGoxVlJnCnFvWlV4eEM4dmVLemJNa2lmUVNp
            cXhYalFnRUJUMWVnVzhFZVBPVWt1RTQKLS0tIGlFdC83QzNQVnBCb1h3eldTRTRQ
            OVJxWkRDdGdFaC9rWnhna0grNi9qZUUKnKOdlr+4ZrBdznsqQNZlrizBPuvHGsMR
            U9sVpgtIzfh+2MjvDE7cADEK9BrmQbQWsa5LECQbvCt7kva5nfxZtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zghrycrgnan0c7nfp5ke5csdeh9rdgtzwsd6yj4pl9rzlzjp24cspycpul
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T13:58:22Z"
    mac: ENC[AES256_GCM,data:YVrX4iCnNdylFIUjQcw4SRvbvQcdIUUEH9vRvcF7XXOp3Fats+M2YW+NXJ6lUsv26AELzVVhhFIC0CTUtNEJ5YVyQJBDfs4tEjoCG1zYlGBRMW3C8BlX5ybvWckiUkrsgawGqFQMVSPxcwzkSTj/J4l9oebWvDUuCtFiGlZbzeE=,iv:Q5wVuPW0A3QqDc5MpZsw0yWC1kb3RnndsCsOh5hbfCI=,tag:DWNbLv+vcm4pgmZpQR6D0g==,type:str]
    version: 3.13.0
