apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uptime-kuma

helmCharts:
  - name: mariadb-cluster
    repo: oci://ghcr.io/mariadb-operator/charts
    version: 26.10.1
    releaseName: mariadb-cluster
    namespace: uptime-kuma
    valuesFile: mariadb-values.yaml
    includeCRDs: false
  - name: app-template
    repo: oci://ghcr.io/nulcell/charts
    version: 0.3.3
    releaseName: uptime-kuma
    namespace: uptime-kuma
    valuesFile: values.yaml
    includeCRDs: false

resources:
  - namespace.yaml
  - mariadb-netpol.yaml
