mariadb:
  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: true

  # Initial database and user. The operator grants the initial user
  # ALL PRIVILEGES on the initial database automatically.
  database: uptime-kuma
  username: uptime-kuma
  passwordSecretKeyRef:
    name: mariadb-uptime-kuma-password
    key: password
    generate: true

  replicas: 1

  galera:
    enabled: false
  replication:
    enabled: false

  storage:
    storageClassName: longhorn
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    max_allowed_packet=256M
    innodb_buffer_pool_size=512M
