apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homarr

helmCharts:
  - name: homarr
    repo: https://homarr-labs.github.io/charts
    version: 8.19.0
    releaseName: homarr
    namespace: homarr
    valuesFile: values.yaml
    includeCRDs: false

resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - homarr-external-secrets.yaml
  - httproute.yaml
