---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-jellyfin-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress-class-name }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: media-server-jellyfin
                port:
                  number: {{ $.Values.jellyfin.service.port }}
